package huimei.speedment.hmdata;

import com.speedment.internal.core.runtime.ApplicationMetadata;
import javax.annotation.Generated;

/**
 * A {@link com.speedment.internal.core.runtime.ApplicationMetadata} class
 * for the {@link com.speedment.config.Project} named hmdata. This class
 * contains the meta data present at code generation time.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class HmdataApplicationMetadata implements ApplicationMetadata {
    
    private final static StringBuilder METADATA = new StringBuilder();
    
    static {
        METADATA.append("import com.speedment.config.parameters.*\n");
        METADATA.append("\n");
        METADATA.append("name = \"hmdata\";\n");
        METADATA.append("packageLocation = \"src/main/java\";\n");
        METADATA.append("packageName = \"huimei.speedment\";\n");
        METADATA.append("enabled = true;\n");
        METADATA.append("expanded = true;\n");
    }
    
    @Override
    public String getMetadata() {
        return METADATA.toString();
    }
}