package huimei.speedment.hmdata;

import com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle;
import huimei.speedment.hmdata.hmdata.hmdata.atccode.impl.AtccodeManagerImpl;
import huimei.speedment.hmdata.hmdata.hmdata.cfdadrug.impl.CfdadrugManagerImpl;
import huimei.speedment.hmdata.hmdata.hmdata.drugcommon.impl.DrugcommonManagerImpl;
import javax.annotation.Generated;

/**
 * A {@link
 * com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle} class
 * for the {@link com.speedment.config.Project} named hmdata.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class HmdataApplication extends SpeedmentApplicationLifecycle<HmdataApplication> {
    
    public HmdataApplication() {
        setSpeedmentApplicationMetadata(new HmdataApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        super.onInit();
        loadAndSetProject();
        put(new AtccodeManagerImpl(speedment));
        put(new CfdadrugManagerImpl(speedment));
        put(new DrugcommonManagerImpl(speedment));
    }
}