package huimei.speedment.hmdata.hmdata.hmdata.atccode;

import com.speedment.Entity;
import com.speedment.field.ComparableField;
import com.speedment.field.StringField;
import com.speedment.internal.core.field.ComparableFieldImpl;
import com.speedment.internal.core.field.StringFieldImpl;
import java.util.Optional;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the
 * com.speedment.internal.ui.config.TableProperty@7f4ab589.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public interface Atccode extends Entity<Atccode> {
    
    /**
     * This Field corresponds to the {@link Atccode} field that can be obtained
     * using the {@link Atccode#getId()} method.
     */
    public final static ComparableField<Atccode, Integer> ID = new ComparableFieldImpl<>("id", Atccode::getId, Atccode::setId);
    /**
     * This Field corresponds to the {@link Atccode} field that can be obtained
     * using the {@link Atccode#getAtcCode()} method.
     */
    public final static StringField<Atccode> ATCCODE = new StringFieldImpl<>("atc_code", o -> o.getAtcCode().orElse(null), Atccode::setAtcCode);
    /**
     * This Field corresponds to the {@link Atccode} field that can be obtained
     * using the {@link Atccode#getName()} method.
     */
    public final static StringField<Atccode> NAME = new StringFieldImpl<>("name", o -> o.getName().orElse(null), Atccode::setName);
    /**
     * This Field corresponds to the {@link Atccode} field that can be obtained
     * using the {@link Atccode#getEnName()} method.
     */
    public final static StringField<Atccode> ENNAME = new StringFieldImpl<>("en_name", o -> o.getEnName().orElse(null), Atccode::setEnName);
    /**
     * This Field corresponds to the {@link Atccode} field that can be obtained
     * using the {@link Atccode#getPage()} method.
     */
    public final static ComparableField<Atccode, Integer> PAGE = new ComparableFieldImpl<>("page", o -> o.getPage().orElse(null), Atccode::setPage);
    
    /**
     * Returns the id of this Atccode. The id field corresponds to the database
     * column hmdata.hmdata.atccode.id.
     * 
     * @return the id of this Atccode
     */
    Integer getId();
    
    /**
     * Returns the atcCode of this Atccode. The atcCode field corresponds to the
     * database column hmdata.hmdata.atccode.atc_code.
     * 
     * @return the atcCode of this Atccode
     */
    Optional<String> getAtcCode();
    
    /**
     * Returns the name of this Atccode. The name field corresponds to the
     * database column hmdata.hmdata.atccode.name.
     * 
     * @return the name of this Atccode
     */
    Optional<String> getName();
    
    /**
     * Returns the enName of this Atccode. The enName field corresponds to the
     * database column hmdata.hmdata.atccode.en_name.
     * 
     * @return the enName of this Atccode
     */
    Optional<String> getEnName();
    
    /**
     * Returns the page of this Atccode. The page field corresponds to the
     * database column hmdata.hmdata.atccode.page.
     * 
     * @return the page of this Atccode
     */
    Optional<Integer> getPage();
    
    /**
     * Sets the id of this Atccode. The id field corresponds to the database
     * column hmdata.hmdata.atccode.id.
     * 
     * @param id to set of this Atccode
     * @return this Atccode instance
     */
    Atccode setId(Integer id);
    
    /**
     * Sets the atcCode of this Atccode. The atcCode field corresponds to the
     * database column hmdata.hmdata.atccode.atc_code.
     * 
     * @param atcCode to set of this Atccode
     * @return this Atccode instance
     */
    Atccode setAtcCode(String atcCode);
    
    /**
     * Sets the name of this Atccode. The name field corresponds to the database
     * column hmdata.hmdata.atccode.name.
     * 
     * @param name to set of this Atccode
     * @return this Atccode instance
     */
    Atccode setName(String name);
    
    /**
     * Sets the enName of this Atccode. The enName field corresponds to the
     * database column hmdata.hmdata.atccode.en_name.
     * 
     * @param enName to set of this Atccode
     * @return this Atccode instance
     */
    Atccode setEnName(String enName);
    
    /**
     * Sets the page of this Atccode. The page field corresponds to the database
     * column hmdata.hmdata.atccode.page.
     * 
     * @param page to set of this Atccode
     * @return this Atccode instance
     */
    Atccode setPage(Integer page);
}