package huimei.speedment.hmdata.hmdata.hmdata.cfdadrug;

import com.speedment.Entity;
import com.speedment.field.ComparableField;
import com.speedment.field.StringField;
import com.speedment.internal.core.field.ComparableFieldImpl;
import com.speedment.internal.core.field.StringFieldImpl;
import java.util.Optional;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the
 * com.speedment.internal.ui.config.TableProperty@25da935b.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public interface Cfdadrug extends Entity<Cfdadrug> {
    
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getId()} method.
     */
    public final static ComparableField<Cfdadrug, Integer> ID = new ComparableFieldImpl<>("id", Cfdadrug::getId, Cfdadrug::setId);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getCfdaId()} method.
     */
    public final static ComparableField<Cfdadrug, Integer> CFDAID = new ComparableFieldImpl<>("cfda_id", o -> o.getCfdaId().orElse(null), Cfdadrug::setCfdaId);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getDrugType()} method.
     */
    public final static StringField<Cfdadrug> DRUGTYPE = new StringFieldImpl<>("drug_type", o -> o.getDrugType().orElse(null), Cfdadrug::setDrugType);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getRegisterNo()} method.
     */
    public final static StringField<Cfdadrug> REGISTERNO = new StringFieldImpl<>("register_no", o -> o.getRegisterNo().orElse(null), Cfdadrug::setRegisterNo);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getOriginalRegisterNo()} method.
     */
    public final static StringField<Cfdadrug> ORIGINALREGISTERNO = new StringFieldImpl<>("original_register_no", o -> o.getOriginalRegisterNo().orElse(null), Cfdadrug::setOriginalRegisterNo);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getApprovalNumber()} method.
     */
    public final static StringField<Cfdadrug> APPROVALNUMBER = new StringFieldImpl<>("approval_number", o -> o.getApprovalNumber().orElse(null), Cfdadrug::setApprovalNumber);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getCnCompanyName()} method.
     */
    public final static StringField<Cfdadrug> CNCOMPANYNAME = new StringFieldImpl<>("cn_company_name", o -> o.getCnCompanyName().orElse(null), Cfdadrug::setCnCompanyName);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getEnCompanyName()} method.
     */
    public final static StringField<Cfdadrug> ENCOMPANYNAME = new StringFieldImpl<>("en_company_name", o -> o.getEnCompanyName().orElse(null), Cfdadrug::setEnCompanyName);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getCnAddress()} method.
     */
    public final static StringField<Cfdadrug> CNADDRESS = new StringFieldImpl<>("cn_address", o -> o.getCnAddress().orElse(null), Cfdadrug::setCnAddress);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getEnAddress()} method.
     */
    public final static StringField<Cfdadrug> ENADDRESS = new StringFieldImpl<>("en_address", o -> o.getEnAddress().orElse(null), Cfdadrug::setEnAddress);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getCnCountriesRegions()} method.
     */
    public final static StringField<Cfdadrug> CNCOUNTRIESREGIONS = new StringFieldImpl<>("cn_countries_regions", o -> o.getCnCountriesRegions().orElse(null), Cfdadrug::setCnCountriesRegions);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getEnCountriesRegions()} method.
     */
    public final static StringField<Cfdadrug> ENCOUNTRIESREGIONS = new StringFieldImpl<>("en_countries_regions", o -> o.getEnCountriesRegions().orElse(null), Cfdadrug::setEnCountriesRegions);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getCnProductName()} method.
     */
    public final static StringField<Cfdadrug> CNPRODUCTNAME = new StringFieldImpl<>("cn_product_name", o -> o.getCnProductName().orElse(null), Cfdadrug::setCnProductName);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getEnProductName()} method.
     */
    public final static StringField<Cfdadrug> ENPRODUCTNAME = new StringFieldImpl<>("en_product_name", o -> o.getEnProductName().orElse(null), Cfdadrug::setEnProductName);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getCnTradeName()} method.
     */
    public final static StringField<Cfdadrug> CNTRADENAME = new StringFieldImpl<>("cn_trade_name", o -> o.getCnTradeName().orElse(null), Cfdadrug::setCnTradeName);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getEnTradeName()} method.
     */
    public final static StringField<Cfdadrug> ENTRADENAME = new StringFieldImpl<>("en_trade_name", o -> o.getEnTradeName().orElse(null), Cfdadrug::setEnTradeName);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getDosageForm()} method.
     */
    public final static StringField<Cfdadrug> DOSAGEFORM = new StringFieldImpl<>("dosage_form", o -> o.getDosageForm().orElse(null), Cfdadrug::setDosageForm);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getSpecification()} method.
     */
    public final static StringField<Cfdadrug> SPECIFICATION = new StringFieldImpl<>("specification", o -> o.getSpecification().orElse(null), Cfdadrug::setSpecification);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getPackingSpecification()} method.
     */
    public final static StringField<Cfdadrug> PACKINGSPECIFICATION = new StringFieldImpl<>("packing_specification", o -> o.getPackingSpecification().orElse(null), Cfdadrug::setPackingSpecification);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getCnManufacturer()} method.
     */
    public final static StringField<Cfdadrug> CNMANUFACTURER = new StringFieldImpl<>("cn_manufacturer", o -> o.getCnManufacturer().orElse(null), Cfdadrug::setCnManufacturer);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getEnManufacturer()} method.
     */
    public final static StringField<Cfdadrug> ENMANUFACTURER = new StringFieldImpl<>("en_manufacturer", o -> o.getEnManufacturer().orElse(null), Cfdadrug::setEnManufacturer);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getCnManufacturerAddr()} method.
     */
    public final static StringField<Cfdadrug> CNMANUFACTURERADDR = new StringFieldImpl<>("cn_manufacturer_addr", o -> o.getCnManufacturerAddr().orElse(null), Cfdadrug::setCnManufacturerAddr);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getEnManufacturerAddr()} method.
     */
    public final static StringField<Cfdadrug> ENMANUFACTURERADDR = new StringFieldImpl<>("en_manufacturer_addr", o -> o.getEnManufacturerAddr().orElse(null), Cfdadrug::setEnManufacturerAddr);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getCnManufacturerRegions()} method.
     */
    public final static StringField<Cfdadrug> CNMANUFACTURERREGIONS = new StringFieldImpl<>("cn_manufacturer_regions", o -> o.getCnManufacturerRegions().orElse(null), Cfdadrug::setCnManufacturerRegions);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getEnManufacturerRegions()} method.
     */
    public final static StringField<Cfdadrug> ENMANUFACTURERREGIONS = new StringFieldImpl<>("en_manufacturer_regions", o -> o.getEnManufacturerRegions().orElse(null), Cfdadrug::setEnManufacturerRegions);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getDateIssue()} method.
     */
    public final static StringField<Cfdadrug> DATEISSUE = new StringFieldImpl<>("date_issue", o -> o.getDateIssue().orElse(null), Cfdadrug::setDateIssue);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getValidityDeadlines()} method.
     */
    public final static StringField<Cfdadrug> VALIDITYDEADLINES = new StringFieldImpl<>("validity_deadlines", o -> o.getValidityDeadlines().orElse(null), Cfdadrug::setValidityDeadlines);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getSubPackCompanyName()} method.
     */
    public final static StringField<Cfdadrug> SUBPACKCOMPANYNAME = new StringFieldImpl<>("sub_pack_company_name", o -> o.getSubPackCompanyName().orElse(null), Cfdadrug::setSubPackCompanyName);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getSubPackCompanyAddr()} method.
     */
    public final static StringField<Cfdadrug> SUBPACKCOMPANYADDR = new StringFieldImpl<>("sub_pack_company_addr", o -> o.getSubPackCompanyAddr().orElse(null), Cfdadrug::setSubPackCompanyAddr);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getSubPackReferenceDate()} method.
     */
    public final static StringField<Cfdadrug> SUBPACKREFERENCEDATE = new StringFieldImpl<>("sub_pack_reference_date", o -> o.getSubPackReferenceDate().orElse(null), Cfdadrug::setSubPackReferenceDate);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getSubPackReferenceDeadlines()} method.
     */
    public final static StringField<Cfdadrug> SUBPACKREFERENCEDEADLINES = new StringFieldImpl<>("sub_pack_reference_deadlines", o -> o.getSubPackReferenceDeadlines().orElse(null), Cfdadrug::setSubPackReferenceDeadlines);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getProductClass()} method.
     */
    public final static StringField<Cfdadrug> PRODUCTCLASS = new StringFieldImpl<>("product_class", o -> o.getProductClass().orElse(null), Cfdadrug::setProductClass);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getStandardCode()} method.
     */
    public final static StringField<Cfdadrug> STANDARDCODE = new StringFieldImpl<>("standard_code", o -> o.getStandardCode().orElse(null), Cfdadrug::setStandardCode);
    /**
     * This Field corresponds to the {@link Cfdadrug} field that can be obtained
     * using the {@link Cfdadrug#getStandardCodeRemark()} method.
     */
    public final static StringField<Cfdadrug> STANDARDCODEREMARK = new StringFieldImpl<>("standard_code_remark", o -> o.getStandardCodeRemark().orElse(null), Cfdadrug::setStandardCodeRemark);
    
    /**
     * Returns the id of this Cfdadrug. The id field corresponds to the database
     * column hmdata.hmdata.cfdadrug.id.
     * 
     * @return the id of this Cfdadrug
     */
    Integer getId();
    
    /**
     * Returns the cfdaId of this Cfdadrug. The cfdaId field corresponds to the
     * database column hmdata.hmdata.cfdadrug.cfda_id.
     * 
     * @return the cfdaId of this Cfdadrug
     */
    Optional<Integer> getCfdaId();
    
    /**
     * Returns the drugType of this Cfdadrug. The drugType field corresponds to
     * the database column hmdata.hmdata.cfdadrug.drug_type.
     * 
     * @return the drugType of this Cfdadrug
     */
    Optional<String> getDrugType();
    
    /**
     * Returns the registerNo of this Cfdadrug. The registerNo field corresponds
     * to the database column hmdata.hmdata.cfdadrug.register_no.
     * 
     * @return the registerNo of this Cfdadrug
     */
    Optional<String> getRegisterNo();
    
    /**
     * Returns the originalRegisterNo of this Cfdadrug. The originalRegisterNo
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.original_register_no.
     * 
     * @return the originalRegisterNo of this Cfdadrug
     */
    Optional<String> getOriginalRegisterNo();
    
    /**
     * Returns the approvalNumber of this Cfdadrug. The approvalNumber field
     * corresponds to the database column hmdata.hmdata.cfdadrug.approval_number.
     * 
     * @return the approvalNumber of this Cfdadrug
     */
    Optional<String> getApprovalNumber();
    
    /**
     * Returns the cnCompanyName of this Cfdadrug. The cnCompanyName field
     * corresponds to the database column hmdata.hmdata.cfdadrug.cn_company_name.
     * 
     * @return the cnCompanyName of this Cfdadrug
     */
    Optional<String> getCnCompanyName();
    
    /**
     * Returns the enCompanyName of this Cfdadrug. The enCompanyName field
     * corresponds to the database column hmdata.hmdata.cfdadrug.en_company_name.
     * 
     * @return the enCompanyName of this Cfdadrug
     */
    Optional<String> getEnCompanyName();
    
    /**
     * Returns the cnAddress of this Cfdadrug. The cnAddress field corresponds to
     * the database column hmdata.hmdata.cfdadrug.cn_address.
     * 
     * @return the cnAddress of this Cfdadrug
     */
    Optional<String> getCnAddress();
    
    /**
     * Returns the enAddress of this Cfdadrug. The enAddress field corresponds to
     * the database column hmdata.hmdata.cfdadrug.en_address.
     * 
     * @return the enAddress of this Cfdadrug
     */
    Optional<String> getEnAddress();
    
    /**
     * Returns the cnCountriesRegions of this Cfdadrug. The cnCountriesRegions
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.cn_countries_regions.
     * 
     * @return the cnCountriesRegions of this Cfdadrug
     */
    Optional<String> getCnCountriesRegions();
    
    /**
     * Returns the enCountriesRegions of this Cfdadrug. The enCountriesRegions
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.en_countries_regions.
     * 
     * @return the enCountriesRegions of this Cfdadrug
     */
    Optional<String> getEnCountriesRegions();
    
    /**
     * Returns the cnProductName of this Cfdadrug. The cnProductName field
     * corresponds to the database column hmdata.hmdata.cfdadrug.cn_product_name.
     * 
     * @return the cnProductName of this Cfdadrug
     */
    Optional<String> getCnProductName();
    
    /**
     * Returns the enProductName of this Cfdadrug. The enProductName field
     * corresponds to the database column hmdata.hmdata.cfdadrug.en_product_name.
     * 
     * @return the enProductName of this Cfdadrug
     */
    Optional<String> getEnProductName();
    
    /**
     * Returns the cnTradeName of this Cfdadrug. The cnTradeName field
     * corresponds to the database column hmdata.hmdata.cfdadrug.cn_trade_name.
     * 
     * @return the cnTradeName of this Cfdadrug
     */
    Optional<String> getCnTradeName();
    
    /**
     * Returns the enTradeName of this Cfdadrug. The enTradeName field
     * corresponds to the database column hmdata.hmdata.cfdadrug.en_trade_name.
     * 
     * @return the enTradeName of this Cfdadrug
     */
    Optional<String> getEnTradeName();
    
    /**
     * Returns the dosageForm of this Cfdadrug. The dosageForm field corresponds
     * to the database column hmdata.hmdata.cfdadrug.dosage_form.
     * 
     * @return the dosageForm of this Cfdadrug
     */
    Optional<String> getDosageForm();
    
    /**
     * Returns the specification of this Cfdadrug. The specification field
     * corresponds to the database column hmdata.hmdata.cfdadrug.specification.
     * 
     * @return the specification of this Cfdadrug
     */
    Optional<String> getSpecification();
    
    /**
     * Returns the packingSpecification of this Cfdadrug. The
     * packingSpecification field corresponds to the database column
     * hmdata.hmdata.cfdadrug.packing_specification.
     * 
     * @return the packingSpecification of this Cfdadrug
     */
    Optional<String> getPackingSpecification();
    
    /**
     * Returns the cnManufacturer of this Cfdadrug. The cnManufacturer field
     * corresponds to the database column hmdata.hmdata.cfdadrug.cn_manufacturer.
     * 
     * @return the cnManufacturer of this Cfdadrug
     */
    Optional<String> getCnManufacturer();
    
    /**
     * Returns the enManufacturer of this Cfdadrug. The enManufacturer field
     * corresponds to the database column hmdata.hmdata.cfdadrug.en_manufacturer.
     * 
     * @return the enManufacturer of this Cfdadrug
     */
    Optional<String> getEnManufacturer();
    
    /**
     * Returns the cnManufacturerAddr of this Cfdadrug. The cnManufacturerAddr
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.cn_manufacturer_addr.
     * 
     * @return the cnManufacturerAddr of this Cfdadrug
     */
    Optional<String> getCnManufacturerAddr();
    
    /**
     * Returns the enManufacturerAddr of this Cfdadrug. The enManufacturerAddr
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.en_manufacturer_addr.
     * 
     * @return the enManufacturerAddr of this Cfdadrug
     */
    Optional<String> getEnManufacturerAddr();
    
    /**
     * Returns the cnManufacturerRegions of this Cfdadrug. The
     * cnManufacturerRegions field corresponds to the database column
     * hmdata.hmdata.cfdadrug.cn_manufacturer_regions.
     * 
     * @return the cnManufacturerRegions of this Cfdadrug
     */
    Optional<String> getCnManufacturerRegions();
    
    /**
     * Returns the enManufacturerRegions of this Cfdadrug. The
     * enManufacturerRegions field corresponds to the database column
     * hmdata.hmdata.cfdadrug.en_manufacturer_regions.
     * 
     * @return the enManufacturerRegions of this Cfdadrug
     */
    Optional<String> getEnManufacturerRegions();
    
    /**
     * Returns the dateIssue of this Cfdadrug. The dateIssue field corresponds to
     * the database column hmdata.hmdata.cfdadrug.date_issue.
     * 
     * @return the dateIssue of this Cfdadrug
     */
    Optional<String> getDateIssue();
    
    /**
     * Returns the validityDeadlines of this Cfdadrug. The validityDeadlines
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.validity_deadlines.
     * 
     * @return the validityDeadlines of this Cfdadrug
     */
    Optional<String> getValidityDeadlines();
    
    /**
     * Returns the subPackCompanyName of this Cfdadrug. The subPackCompanyName
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.sub_pack_company_name.
     * 
     * @return the subPackCompanyName of this Cfdadrug
     */
    Optional<String> getSubPackCompanyName();
    
    /**
     * Returns the subPackCompanyAddr of this Cfdadrug. The subPackCompanyAddr
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.sub_pack_company_addr.
     * 
     * @return the subPackCompanyAddr of this Cfdadrug
     */
    Optional<String> getSubPackCompanyAddr();
    
    /**
     * Returns the subPackReferenceDate of this Cfdadrug. The
     * subPackReferenceDate field corresponds to the database column
     * hmdata.hmdata.cfdadrug.sub_pack_reference_date.
     * 
     * @return the subPackReferenceDate of this Cfdadrug
     */
    Optional<String> getSubPackReferenceDate();
    
    /**
     * Returns the subPackReferenceDeadlines of this Cfdadrug. The
     * subPackReferenceDeadlines field corresponds to the database column
     * hmdata.hmdata.cfdadrug.sub_pack_reference_deadlines.
     * 
     * @return the subPackReferenceDeadlines of this Cfdadrug
     */
    Optional<String> getSubPackReferenceDeadlines();
    
    /**
     * Returns the productClass of this Cfdadrug. The productClass field
     * corresponds to the database column hmdata.hmdata.cfdadrug.product_class.
     * 
     * @return the productClass of this Cfdadrug
     */
    Optional<String> getProductClass();
    
    /**
     * Returns the standardCode of this Cfdadrug. The standardCode field
     * corresponds to the database column hmdata.hmdata.cfdadrug.standard_code.
     * 
     * @return the standardCode of this Cfdadrug
     */
    Optional<String> getStandardCode();
    
    /**
     * Returns the standardCodeRemark of this Cfdadrug. The standardCodeRemark
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.standard_code_remark.
     * 
     * @return the standardCodeRemark of this Cfdadrug
     */
    Optional<String> getStandardCodeRemark();
    
    /**
     * Sets the id of this Cfdadrug. The id field corresponds to the database
     * column hmdata.hmdata.cfdadrug.id.
     * 
     * @param id to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setId(Integer id);
    
    /**
     * Sets the cfdaId of this Cfdadrug. The cfdaId field corresponds to the
     * database column hmdata.hmdata.cfdadrug.cfda_id.
     * 
     * @param cfdaId to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setCfdaId(Integer cfdaId);
    
    /**
     * Sets the drugType of this Cfdadrug. The drugType field corresponds to the
     * database column hmdata.hmdata.cfdadrug.drug_type.
     * 
     * @param drugType to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setDrugType(String drugType);
    
    /**
     * Sets the registerNo of this Cfdadrug. The registerNo field corresponds to
     * the database column hmdata.hmdata.cfdadrug.register_no.
     * 
     * @param registerNo to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setRegisterNo(String registerNo);
    
    /**
     * Sets the originalRegisterNo of this Cfdadrug. The originalRegisterNo field
     * corresponds to the database column
     * hmdata.hmdata.cfdadrug.original_register_no.
     * 
     * @param originalRegisterNo to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setOriginalRegisterNo(String originalRegisterNo);
    
    /**
     * Sets the approvalNumber of this Cfdadrug. The approvalNumber field
     * corresponds to the database column hmdata.hmdata.cfdadrug.approval_number.
     * 
     * @param approvalNumber to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setApprovalNumber(String approvalNumber);
    
    /**
     * Sets the cnCompanyName of this Cfdadrug. The cnCompanyName field
     * corresponds to the database column hmdata.hmdata.cfdadrug.cn_company_name.
     * 
     * @param cnCompanyName to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setCnCompanyName(String cnCompanyName);
    
    /**
     * Sets the enCompanyName of this Cfdadrug. The enCompanyName field
     * corresponds to the database column hmdata.hmdata.cfdadrug.en_company_name.
     * 
     * @param enCompanyName to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setEnCompanyName(String enCompanyName);
    
    /**
     * Sets the cnAddress of this Cfdadrug. The cnAddress field corresponds to
     * the database column hmdata.hmdata.cfdadrug.cn_address.
     * 
     * @param cnAddress to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setCnAddress(String cnAddress);
    
    /**
     * Sets the enAddress of this Cfdadrug. The enAddress field corresponds to
     * the database column hmdata.hmdata.cfdadrug.en_address.
     * 
     * @param enAddress to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setEnAddress(String enAddress);
    
    /**
     * Sets the cnCountriesRegions of this Cfdadrug. The cnCountriesRegions field
     * corresponds to the database column
     * hmdata.hmdata.cfdadrug.cn_countries_regions.
     * 
     * @param cnCountriesRegions to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setCnCountriesRegions(String cnCountriesRegions);
    
    /**
     * Sets the enCountriesRegions of this Cfdadrug. The enCountriesRegions field
     * corresponds to the database column
     * hmdata.hmdata.cfdadrug.en_countries_regions.
     * 
     * @param enCountriesRegions to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setEnCountriesRegions(String enCountriesRegions);
    
    /**
     * Sets the cnProductName of this Cfdadrug. The cnProductName field
     * corresponds to the database column hmdata.hmdata.cfdadrug.cn_product_name.
     * 
     * @param cnProductName to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setCnProductName(String cnProductName);
    
    /**
     * Sets the enProductName of this Cfdadrug. The enProductName field
     * corresponds to the database column hmdata.hmdata.cfdadrug.en_product_name.
     * 
     * @param enProductName to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setEnProductName(String enProductName);
    
    /**
     * Sets the cnTradeName of this Cfdadrug. The cnTradeName field corresponds
     * to the database column hmdata.hmdata.cfdadrug.cn_trade_name.
     * 
     * @param cnTradeName to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setCnTradeName(String cnTradeName);
    
    /**
     * Sets the enTradeName of this Cfdadrug. The enTradeName field corresponds
     * to the database column hmdata.hmdata.cfdadrug.en_trade_name.
     * 
     * @param enTradeName to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setEnTradeName(String enTradeName);
    
    /**
     * Sets the dosageForm of this Cfdadrug. The dosageForm field corresponds to
     * the database column hmdata.hmdata.cfdadrug.dosage_form.
     * 
     * @param dosageForm to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setDosageForm(String dosageForm);
    
    /**
     * Sets the specification of this Cfdadrug. The specification field
     * corresponds to the database column hmdata.hmdata.cfdadrug.specification.
     * 
     * @param specification to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setSpecification(String specification);
    
    /**
     * Sets the packingSpecification of this Cfdadrug. The packingSpecification
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.packing_specification.
     * 
     * @param packingSpecification to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setPackingSpecification(String packingSpecification);
    
    /**
     * Sets the cnManufacturer of this Cfdadrug. The cnManufacturer field
     * corresponds to the database column hmdata.hmdata.cfdadrug.cn_manufacturer.
     * 
     * @param cnManufacturer to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setCnManufacturer(String cnManufacturer);
    
    /**
     * Sets the enManufacturer of this Cfdadrug. The enManufacturer field
     * corresponds to the database column hmdata.hmdata.cfdadrug.en_manufacturer.
     * 
     * @param enManufacturer to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setEnManufacturer(String enManufacturer);
    
    /**
     * Sets the cnManufacturerAddr of this Cfdadrug. The cnManufacturerAddr field
     * corresponds to the database column
     * hmdata.hmdata.cfdadrug.cn_manufacturer_addr.
     * 
     * @param cnManufacturerAddr to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setCnManufacturerAddr(String cnManufacturerAddr);
    
    /**
     * Sets the enManufacturerAddr of this Cfdadrug. The enManufacturerAddr field
     * corresponds to the database column
     * hmdata.hmdata.cfdadrug.en_manufacturer_addr.
     * 
     * @param enManufacturerAddr to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setEnManufacturerAddr(String enManufacturerAddr);
    
    /**
     * Sets the cnManufacturerRegions of this Cfdadrug. The cnManufacturerRegions
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.cn_manufacturer_regions.
     * 
     * @param cnManufacturerRegions to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setCnManufacturerRegions(String cnManufacturerRegions);
    
    /**
     * Sets the enManufacturerRegions of this Cfdadrug. The enManufacturerRegions
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.en_manufacturer_regions.
     * 
     * @param enManufacturerRegions to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setEnManufacturerRegions(String enManufacturerRegions);
    
    /**
     * Sets the dateIssue of this Cfdadrug. The dateIssue field corresponds to
     * the database column hmdata.hmdata.cfdadrug.date_issue.
     * 
     * @param dateIssue to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setDateIssue(String dateIssue);
    
    /**
     * Sets the validityDeadlines of this Cfdadrug. The validityDeadlines field
     * corresponds to the database column
     * hmdata.hmdata.cfdadrug.validity_deadlines.
     * 
     * @param validityDeadlines to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setValidityDeadlines(String validityDeadlines);
    
    /**
     * Sets the subPackCompanyName of this Cfdadrug. The subPackCompanyName field
     * corresponds to the database column
     * hmdata.hmdata.cfdadrug.sub_pack_company_name.
     * 
     * @param subPackCompanyName to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setSubPackCompanyName(String subPackCompanyName);
    
    /**
     * Sets the subPackCompanyAddr of this Cfdadrug. The subPackCompanyAddr field
     * corresponds to the database column
     * hmdata.hmdata.cfdadrug.sub_pack_company_addr.
     * 
     * @param subPackCompanyAddr to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setSubPackCompanyAddr(String subPackCompanyAddr);
    
    /**
     * Sets the subPackReferenceDate of this Cfdadrug. The subPackReferenceDate
     * field corresponds to the database column
     * hmdata.hmdata.cfdadrug.sub_pack_reference_date.
     * 
     * @param subPackReferenceDate to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setSubPackReferenceDate(String subPackReferenceDate);
    
    /**
     * Sets the subPackReferenceDeadlines of this Cfdadrug. The
     * subPackReferenceDeadlines field corresponds to the database column
     * hmdata.hmdata.cfdadrug.sub_pack_reference_deadlines.
     * 
     * @param subPackReferenceDeadlines to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setSubPackReferenceDeadlines(String subPackReferenceDeadlines);
    
    /**
     * Sets the productClass of this Cfdadrug. The productClass field corresponds
     * to the database column hmdata.hmdata.cfdadrug.product_class.
     * 
     * @param productClass to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setProductClass(String productClass);
    
    /**
     * Sets the standardCode of this Cfdadrug. The standardCode field corresponds
     * to the database column hmdata.hmdata.cfdadrug.standard_code.
     * 
     * @param standardCode to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setStandardCode(String standardCode);
    
    /**
     * Sets the standardCodeRemark of this Cfdadrug. The standardCodeRemark field
     * corresponds to the database column
     * hmdata.hmdata.cfdadrug.standard_code_remark.
     * 
     * @param standardCodeRemark to set of this Cfdadrug
     * @return this Cfdadrug instance
     */
    Cfdadrug setStandardCodeRemark(String standardCodeRemark);
}